/**
 * generated by Xtext 2.12.0
 */
package com.bmstu.iptables.xtext.ide;

import com.bmstu.iptables.xtext.LanguageRuntimeModule;
import com.bmstu.iptables.xtext.LanguageStandaloneSetup;
import com.bmstu.iptables.xtext.ide.LanguageIdeModule;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class LanguageIdeSetup extends LanguageStandaloneSetup {
  @Override
  public Injector createInjector() {
    LanguageRuntimeModule _languageRuntimeModule = new LanguageRuntimeModule();
    LanguageIdeModule _languageIdeModule = new LanguageIdeModule();
    return Guice.createInjector(Modules2.mixin(_languageRuntimeModule, _languageIdeModule));
  }
}
