/**
 * generated by Xtext 2.12.0
 */
package com.bmstu.iptables.xtext.ui.contentassist;

import com.bmstu.iptables.xtext.ui.contentassist.AbstractLanguageProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class LanguageProposalProvider extends AbstractLanguageProposalProvider {
}
