/**
 * generated by Xtext 2.12.0
 */
package com.bmstu.iptables.xtext;

import com.bmstu.iptables.xtext.AbstractLanguageRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class LanguageRuntimeModule extends AbstractLanguageRuntimeModule {
}
