/*
 * generated by Xtext 2.12.0
 */
package com.bmstu.iptables.xtext.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class LanguageUiModule extends AbstractLanguageUiModule {
}
