/**
 * generated by Xtext 2.12.0
 */
package com.bmstu.iptables.xtext.language;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see com.bmstu.iptables.xtext.language.LanguageFactory
 * @model kind="package"
 * @generated
 */
public interface LanguagePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "language";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.bmstu.com/iptables/xtext/Language";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "language";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  LanguagePackage eINSTANCE = com.bmstu.iptables.xtext.language.impl.LanguagePackageImpl.init();

  /**
   * The meta object id for the '{@link com.bmstu.iptables.xtext.language.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.bmstu.iptables.xtext.language.impl.ModelImpl
   * @see com.bmstu.iptables.xtext.language.impl.LanguagePackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Chains</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__CHAINS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.bmstu.iptables.xtext.language.impl.ChainImpl <em>Chain</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.bmstu.iptables.xtext.language.impl.ChainImpl
   * @see com.bmstu.iptables.xtext.language.impl.LanguagePackageImpl#getChain()
   * @generated
   */
  int CHAIN = 1;

  /**
   * The feature id for the '<em><b>Chain Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHAIN__CHAIN_TYPE = 0;

  /**
   * The feature id for the '<em><b>Policy Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHAIN__POLICY_TYPE = 1;

  /**
   * The feature id for the '<em><b>Parts</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHAIN__PARTS = 2;

  /**
   * The number of structural features of the '<em>Chain</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHAIN_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link com.bmstu.iptables.xtext.language.impl.ChainPartImpl <em>Chain Part</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.bmstu.iptables.xtext.language.impl.ChainPartImpl
   * @see com.bmstu.iptables.xtext.language.impl.LanguagePackageImpl#getChainPart()
   * @generated
   */
  int CHAIN_PART = 2;

  /**
   * The feature id for the '<em><b>Target</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHAIN_PART__TARGET = 0;

  /**
   * The feature id for the '<em><b>Prot</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHAIN_PART__PROT = 1;

  /**
   * The feature id for the '<em><b>Opt</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHAIN_PART__OPT = 2;

  /**
   * The feature id for the '<em><b>Source</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHAIN_PART__SOURCE = 3;

  /**
   * The feature id for the '<em><b>Destination</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHAIN_PART__DESTINATION = 4;

  /**
   * The number of structural features of the '<em>Chain Part</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHAIN_PART_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link com.bmstu.iptables.xtext.language.ChainType <em>Chain Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.bmstu.iptables.xtext.language.ChainType
   * @see com.bmstu.iptables.xtext.language.impl.LanguagePackageImpl#getChainType()
   * @generated
   */
  int CHAIN_TYPE = 3;

  /**
   * The meta object id for the '{@link com.bmstu.iptables.xtext.language.PolicyType <em>Policy Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.bmstu.iptables.xtext.language.PolicyType
   * @see com.bmstu.iptables.xtext.language.impl.LanguagePackageImpl#getPolicyType()
   * @generated
   */
  int POLICY_TYPE = 4;


  /**
   * Returns the meta object for class '{@link com.bmstu.iptables.xtext.language.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see com.bmstu.iptables.xtext.language.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link com.bmstu.iptables.xtext.language.Model#getChains <em>Chains</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Chains</em>'.
   * @see com.bmstu.iptables.xtext.language.Model#getChains()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Chains();

  /**
   * Returns the meta object for class '{@link com.bmstu.iptables.xtext.language.Chain <em>Chain</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Chain</em>'.
   * @see com.bmstu.iptables.xtext.language.Chain
   * @generated
   */
  EClass getChain();

  /**
   * Returns the meta object for the attribute '{@link com.bmstu.iptables.xtext.language.Chain#getChainType <em>Chain Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Chain Type</em>'.
   * @see com.bmstu.iptables.xtext.language.Chain#getChainType()
   * @see #getChain()
   * @generated
   */
  EAttribute getChain_ChainType();

  /**
   * Returns the meta object for the attribute '{@link com.bmstu.iptables.xtext.language.Chain#getPolicyType <em>Policy Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Policy Type</em>'.
   * @see com.bmstu.iptables.xtext.language.Chain#getPolicyType()
   * @see #getChain()
   * @generated
   */
  EAttribute getChain_PolicyType();

  /**
   * Returns the meta object for the containment reference list '{@link com.bmstu.iptables.xtext.language.Chain#getParts <em>Parts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Parts</em>'.
   * @see com.bmstu.iptables.xtext.language.Chain#getParts()
   * @see #getChain()
   * @generated
   */
  EReference getChain_Parts();

  /**
   * Returns the meta object for class '{@link com.bmstu.iptables.xtext.language.ChainPart <em>Chain Part</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Chain Part</em>'.
   * @see com.bmstu.iptables.xtext.language.ChainPart
   * @generated
   */
  EClass getChainPart();

  /**
   * Returns the meta object for the attribute '{@link com.bmstu.iptables.xtext.language.ChainPart#getTarget <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Target</em>'.
   * @see com.bmstu.iptables.xtext.language.ChainPart#getTarget()
   * @see #getChainPart()
   * @generated
   */
  EAttribute getChainPart_Target();

  /**
   * Returns the meta object for the attribute '{@link com.bmstu.iptables.xtext.language.ChainPart#getProt <em>Prot</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Prot</em>'.
   * @see com.bmstu.iptables.xtext.language.ChainPart#getProt()
   * @see #getChainPart()
   * @generated
   */
  EAttribute getChainPart_Prot();

  /**
   * Returns the meta object for the attribute '{@link com.bmstu.iptables.xtext.language.ChainPart#getOpt <em>Opt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Opt</em>'.
   * @see com.bmstu.iptables.xtext.language.ChainPart#getOpt()
   * @see #getChainPart()
   * @generated
   */
  EAttribute getChainPart_Opt();

  /**
   * Returns the meta object for the attribute '{@link com.bmstu.iptables.xtext.language.ChainPart#getSource <em>Source</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Source</em>'.
   * @see com.bmstu.iptables.xtext.language.ChainPart#getSource()
   * @see #getChainPart()
   * @generated
   */
  EAttribute getChainPart_Source();

  /**
   * Returns the meta object for the attribute '{@link com.bmstu.iptables.xtext.language.ChainPart#getDestination <em>Destination</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Destination</em>'.
   * @see com.bmstu.iptables.xtext.language.ChainPart#getDestination()
   * @see #getChainPart()
   * @generated
   */
  EAttribute getChainPart_Destination();

  /**
   * Returns the meta object for enum '{@link com.bmstu.iptables.xtext.language.ChainType <em>Chain Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Chain Type</em>'.
   * @see com.bmstu.iptables.xtext.language.ChainType
   * @generated
   */
  EEnum getChainType();

  /**
   * Returns the meta object for enum '{@link com.bmstu.iptables.xtext.language.PolicyType <em>Policy Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Policy Type</em>'.
   * @see com.bmstu.iptables.xtext.language.PolicyType
   * @generated
   */
  EEnum getPolicyType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  LanguageFactory getLanguageFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link com.bmstu.iptables.xtext.language.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.bmstu.iptables.xtext.language.impl.ModelImpl
     * @see com.bmstu.iptables.xtext.language.impl.LanguagePackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Chains</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__CHAINS = eINSTANCE.getModel_Chains();

    /**
     * The meta object literal for the '{@link com.bmstu.iptables.xtext.language.impl.ChainImpl <em>Chain</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.bmstu.iptables.xtext.language.impl.ChainImpl
     * @see com.bmstu.iptables.xtext.language.impl.LanguagePackageImpl#getChain()
     * @generated
     */
    EClass CHAIN = eINSTANCE.getChain();

    /**
     * The meta object literal for the '<em><b>Chain Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHAIN__CHAIN_TYPE = eINSTANCE.getChain_ChainType();

    /**
     * The meta object literal for the '<em><b>Policy Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHAIN__POLICY_TYPE = eINSTANCE.getChain_PolicyType();

    /**
     * The meta object literal for the '<em><b>Parts</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHAIN__PARTS = eINSTANCE.getChain_Parts();

    /**
     * The meta object literal for the '{@link com.bmstu.iptables.xtext.language.impl.ChainPartImpl <em>Chain Part</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.bmstu.iptables.xtext.language.impl.ChainPartImpl
     * @see com.bmstu.iptables.xtext.language.impl.LanguagePackageImpl#getChainPart()
     * @generated
     */
    EClass CHAIN_PART = eINSTANCE.getChainPart();

    /**
     * The meta object literal for the '<em><b>Target</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHAIN_PART__TARGET = eINSTANCE.getChainPart_Target();

    /**
     * The meta object literal for the '<em><b>Prot</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHAIN_PART__PROT = eINSTANCE.getChainPart_Prot();

    /**
     * The meta object literal for the '<em><b>Opt</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHAIN_PART__OPT = eINSTANCE.getChainPart_Opt();

    /**
     * The meta object literal for the '<em><b>Source</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHAIN_PART__SOURCE = eINSTANCE.getChainPart_Source();

    /**
     * The meta object literal for the '<em><b>Destination</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHAIN_PART__DESTINATION = eINSTANCE.getChainPart_Destination();

    /**
     * The meta object literal for the '{@link com.bmstu.iptables.xtext.language.ChainType <em>Chain Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.bmstu.iptables.xtext.language.ChainType
     * @see com.bmstu.iptables.xtext.language.impl.LanguagePackageImpl#getChainType()
     * @generated
     */
    EEnum CHAIN_TYPE = eINSTANCE.getChainType();

    /**
     * The meta object literal for the '{@link com.bmstu.iptables.xtext.language.PolicyType <em>Policy Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.bmstu.iptables.xtext.language.PolicyType
     * @see com.bmstu.iptables.xtext.language.impl.LanguagePackageImpl#getPolicyType()
     * @generated
     */
    EEnum POLICY_TYPE = eINSTANCE.getPolicyType();

  }

} //LanguagePackage
