/*
 * generated by Xtext 2.12.0
 */
package com.bmstu.iptables.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractLanguageScopeProvider extends DelegatingScopeProvider {
}
