/**
 * generated by Xtext 2.12.0
 */
package com.bmstu.iptables.xtext.ui;

import com.bmstu.iptables.xtext.ui.AbstractLanguageUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class LanguageUiModule extends AbstractLanguageUiModule {
  public LanguageUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
