/**
 * generated by Xtext 2.12.0
 */
package com.bmstu.iptables.xtext.ide;

import com.bmstu.iptables.xtext.ide.AbstractLanguageIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class LanguageIdeModule extends AbstractLanguageIdeModule {
}
