/**
 * generated by Xtext 2.12.0
 */
package com.bmstu.iptables.xtext.language;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Chain</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.bmstu.iptables.xtext.language.Chain#getChainType <em>Chain Type</em>}</li>
 *   <li>{@link com.bmstu.iptables.xtext.language.Chain#getPolicyType <em>Policy Type</em>}</li>
 *   <li>{@link com.bmstu.iptables.xtext.language.Chain#getParts <em>Parts</em>}</li>
 * </ul>
 *
 * @see com.bmstu.iptables.xtext.language.LanguagePackage#getChain()
 * @model
 * @generated
 */
public interface Chain extends EObject
{
  /**
   * Returns the value of the '<em><b>Chain Type</b></em>' attribute.
   * The literals are from the enumeration {@link com.bmstu.iptables.xtext.language.ChainType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Chain Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Chain Type</em>' attribute.
   * @see com.bmstu.iptables.xtext.language.ChainType
   * @see #setChainType(ChainType)
   * @see com.bmstu.iptables.xtext.language.LanguagePackage#getChain_ChainType()
   * @model
   * @generated
   */
  ChainType getChainType();

  /**
   * Sets the value of the '{@link com.bmstu.iptables.xtext.language.Chain#getChainType <em>Chain Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Chain Type</em>' attribute.
   * @see com.bmstu.iptables.xtext.language.ChainType
   * @see #getChainType()
   * @generated
   */
  void setChainType(ChainType value);

  /**
   * Returns the value of the '<em><b>Policy Type</b></em>' attribute.
   * The literals are from the enumeration {@link com.bmstu.iptables.xtext.language.PolicyType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Policy Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Policy Type</em>' attribute.
   * @see com.bmstu.iptables.xtext.language.PolicyType
   * @see #setPolicyType(PolicyType)
   * @see com.bmstu.iptables.xtext.language.LanguagePackage#getChain_PolicyType()
   * @model
   * @generated
   */
  PolicyType getPolicyType();

  /**
   * Sets the value of the '{@link com.bmstu.iptables.xtext.language.Chain#getPolicyType <em>Policy Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Policy Type</em>' attribute.
   * @see com.bmstu.iptables.xtext.language.PolicyType
   * @see #getPolicyType()
   * @generated
   */
  void setPolicyType(PolicyType value);

  /**
   * Returns the value of the '<em><b>Parts</b></em>' containment reference list.
   * The list contents are of type {@link com.bmstu.iptables.xtext.language.ChainPart}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Parts</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parts</em>' containment reference list.
   * @see com.bmstu.iptables.xtext.language.LanguagePackage#getChain_Parts()
   * @model containment="true"
   * @generated
   */
  EList<ChainPart> getParts();

} // Chain
