/**
 * generated by Xtext 2.12.0
 */
package com.bmstu.iptables.xtext.language;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.bmstu.iptables.xtext.language.Model#getChains <em>Chains</em>}</li>
 * </ul>
 *
 * @see com.bmstu.iptables.xtext.language.LanguagePackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Chains</b></em>' containment reference list.
   * The list contents are of type {@link com.bmstu.iptables.xtext.language.Chain}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Chains</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Chains</em>' containment reference list.
   * @see com.bmstu.iptables.xtext.language.LanguagePackage#getModel_Chains()
   * @model containment="true"
   * @generated
   */
  EList<Chain> getChains();

} // Model
