/*
 * generated by Xtext 2.12.0
 */
package com.bmstu.iptables.xtext.ui.tests;

import com.bmstu.iptables.xtext.ui.internal.XtextActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class LanguageUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("com.bmstu.iptables.xtext.Language");
	}

}
